services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    environment:
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./client/package.json

  server:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/config.env
    environment:
      - PORT=5000
      - DB_URL=mongodb://database:27017/photo_ratu
    depends_on:
      - database
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  backup:
    image: mongo:latest
    depends_on:
      - database
    volumes:
      - ./db_backups:/backups
    command: >
      bash -c "
      while true; do
        TIMESTAMP=$$(date +'%Y-%m-%d');
        echo 'Роблю бекап бази даних...';
        mongodump --uri='mongodb://database:27017/photo_ratu' --out=/backups/dump_$$TIMESTAMP;
        
        echo 'Видаляю бекапи старші за 7 днів...';
        find /backups -maxdepth 1 -name 'dump_*' -type d -mtime +7 -exec rm -rf {} +;
        
        sleep 86400;
      done
      "
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client

volumes:
  db-data:
